name: Build the thesis and deploy on GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Install Inkscape
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends inkscape
      - name: Compile final version
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: final.tex
      - name: Compile printing version
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: printing.tex
      - name: Upload final version
        uses: actions/upload-artifact@v4.6.0
        with:
          name: final.pdf
          path: final.pdf
      - name: Upload printing version
        uses: actions/upload-artifact@v4.6.0
        with:
          name: printing.pdf
          path: printing.pdf

  deploy:
    needs: build

    concurrency:
      group: "pages"
      cancel-in-progress: false

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download final version
        uses: actions/download-artifact@v4.1.8
        with:
          name: final.pdf
          path: github-pages/

      - name: Download printing version
        uses: actions/download-artifact@v4.1.8
        with:
          name: printing.pdf
          path: github-pages/

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: github-pages/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
